### ISSUE TITLE
Poor performance - applications lock up

### ISSUE THREAD

**Issue by PhilipSkinner** [in2core/screenportsdk#4]
## Expected Behaviour

Can run 1080 video at fullscreen for extended periods of time without any lagging or crashes.

## Actual behaviour

1080 video streams for a short while (less than a minute), starts being choppy then eventually stops responding. The application becomes unresponsive and needs to be terminated.

Video of the behaviour when using the SDK:

https://vimeo.com/786549947

Here is a video of the same source being played through the ScreenPort application:

https://vimeo.com/786550499

## Steps to reproduce the problem

* Get signal generator to output a pattern similar to the one in the video (Phabrix Sx - HD 1080i YCbCr-422-10 @ 60fps - zone plate with red box, moving zone-2h)
* Connect to screenport device through BNC
* Connect to ipad through USB
* Run demo application
* Confirm video is playing
* Wait for video to become laggy and stop

**Comment by PhilipSkinner** [comment]
I decided to look at the differences between my application and the demo application and I found that the performance issue goes away when I give the application the relevant permissions for discovering the ScreenPort device on the network as well as via USB.

The performance issue occurs only when an application is written that only expects USB connections.

**Comment by michal-tomlein** [comment]
Thank you, that should help us narrow it down significantly.

**Comment by michal-tomlein** [comment]
We can confirm the issue goes away when you add the `NSBonjourServices` key to `Info.plist`. Our best guess is that the `usbmuxd` socket powering USB communication on iOS requires networking permissions. This is not an issue on macOS, where we use IOKit.

We think it’s very likely the issue is not in our code. We have decided not to invest more time into finding a fix, given that an acceptable workaround is available.
